counters:
  weather:
    montreal: 1
    washington: 1
    toronto: 1

  trips:
    montreal: 1
    washington: 1
    toronto: 1

  stations:
    montreal: 1
    washington: 1
    toronto: 1

  rainjoiner:
    montreal: 1
    washington: 1
    toronto: 1

  yearjoiner:
    montreal: 1
    washington: 1
    toronto: 1

  montrealjoiner:
    montreal: 1

responses:
  weather: ["weather-rainjoiner-topic"]
  trips: ["trips-rainjoiner-topic", "trips-montrealjoiner-topic", "trips-yearjoiner-topic"]
  stations: ["stations-montrealjoiner-topic", "stations-yearjoiner-topic"]

eof_queue_config:
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false

exchanges:
  - weather-rainjoiner-topic
  - stations-montrealjoiner-topic
  - stations-yearjoiner-topic

# ToDo: declare the rest of the exchanges and queues