eof_type: "EOF"

# FIXME: update counters
counters:
  weather-worker:
    montreal: 1
    washington: 1
    toronto: 1

  trips-worker:
    montreal: 1
    washington: 1
    toronto: 1

  stations-worker:
    montreal: 1
    washington: 1
    toronto: 1

  rain-joiner:
    montreal: 1
    washington: 1
    toronto: 1

  year-joiner:
    montreal: 1
    washington: 1
    toronto: 1

  city-joiner:
    montreal: 1

responses:
  weather-worker: ["weather-rainjoiner-topic"]
  trips-worker: ["trips-rainjoiner-topic", "trips-cityjoiner-topic", "trips-yearjoiner-topic"]
  stations-worker: ["stations-cityjoiner-topic", "stations-yearjoiner-topic"]

  rain-joiner: ["rainjoiner-rainhandler-queue"]
  city-joiner: ["cityjoiner-cityhandler-queue"]
  year-joiner: ["cityjoiner-yeargrouper2016-queue", "cityjoiner-yeargrouper2017-queue"]


eof_queue_config:
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false

exchanges:
  - weather-rainjoiner-topic
  - stations-cityjoiner-topic
  - stations-yearjoiner-topic

# ToDo: declare the rest of the exchanges and queues