counters:
  weather:
    montreal: 1
    washington: 1
    toronto: 1

  stations:
    montreal: 1
    washington: 1
    toronto: 1

  rainjoiner:
    montreal: 1
    washington: 1
    toronto: 1

  duplicatejoiner:
    montreal: 1
    washington: 1
    toronto: 1

  montrealjoiner:
    montreal: 1

responses:
  weather: ["weather-rain-joiner-topic"]

  stations: ["stations-montreal-joiner-topic", "stations-duplicate-joiner-topic"]

eof_queue_config:
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false

exchanges:
  - weather-rain-joiner-topic
  - stations-montreal-joiner-topic
  - stations-duplicate-joiner-topic

# ToDo: declare the rest of the exchanges and queues