eof_type: "EOF"

counters:
  weather-worker:
    montreal: 1
    washington: 1
    toronto: 1

  trips-worker:
    montreal: 1
    washington: 1
    toronto: 1

  stations-worker:
    montreal: 1
    washington: 1
    toronto: 1

  rain-joiner:
    montreal: 1
    washington: 1
    toronto: 1

  year-joiner:
    montreal: 1
    washington: 1
    toronto: 1

  montreal-joiner:
    montreal: 1

responses:
  weather-worker: ["weather-rainjoiner-topic"]
  trips-worker: ["trips-rainjoiner-topic", "trips-montrealjoiner-topic", "trips-yearjoiner-topic"]
  stations-worker: ["stations-montrealjoiner-topic", "stations-yearjoiner-topic"]

eof_queue_config:
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false

exchanges:
  - weather-rainjoiner-topic
  - stations-montrealjoiner-topic
  - stations-yearjoiner-topic

# ToDo: declare the rest of the exchanges and queues