eof_type: "EOF"
query_handlers: ["rain-handler", "city-handler", "duplicates-handler"]
special_cases: ["rain-joiner"]

counters:
  weather-worker:
    montreal: 3
    washington: 3
    toronto: 3

  trips-worker:
    montreal: 3
    washington: 3
    toronto: 3

  stations-worker:
    montreal: 3
    washington: 3
    toronto: 3

  rain-joiner: #special case
    montreal: 4
    washington: 4
    toronto: 4

  year-joiner:
    montreal: 4
    washington: 4
    toronto: 4

  city-joiner:
    montreal: 4

  #distance-calculator:
  #  montreal: 4

  rain-handler:
    nn: 1

  duplicates-handler:
    montreal: 1
    washington: 1
    toronto: 1

  city-handler:
    montreal: 1

responses:
  weather-worker: ["weather-rainjoiner-topic"]
  trips-worker: ["trips-rainjoiner-topic", "trips-cityjoiner-topic", "trips-yearjoiner-topic"]
  stations-worker: ["stations-cityjoiner-topic", "stations-yearjoiner-topic"]

  rain-joiner: ["rainjoiner-rainhandler-queue"]
  city-joiner: ["cityjoiner-cityhandler-%s-queue"]
  #distance-calculator: ["distancecalculator-cityhandler-topic"]
  year-joiner: ["yearjoiner-duplicateshandler-%s-queue"]

  rain-handler: ["response-queue"]
  city-handler: ["response-queue"]
  duplicates-handler: ["response-queue"]


input_queue:
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: false
  no_wait: false

exchanges:
  - weather-rainjoiner-topic
  - stations-cityjoiner-topic
  - stations-yearjoiner-topic