rainfall_threshold: 30.0

valid_columns:
  date: 2
  rainfall: 3


rabbit_mq:
  weather:
    exchange_input_weather: # messages from server to weather-worker
      exchange_declaration_config:
        name: "weather-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false


    exchange_output_weather: # messages from weather-worker to rain accumulator
      exchange_declaration_config:
        name: "weather-rain-joiner-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false