rainfall_threshold: 30.0

valid_columns:
  date: 2
  rainfall: 3


rabbit_mq:
  weather:
    exchange_input_weather: # messages from server to X-broker
      exchange_declaration_config:
        name: "weather_topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

      consumption_config:
        exchange: "weather_topic"
        mandatory: false
        immediate: false
        content_type: "text/plain"

      queue_declaration_config: # Anonymous queue for consuming messages
        durable: true
        delete_when_unused: false
        exclusive: true
        no_wait: false

    exchange_output_weather: # messages from X-broker to rain accumulator
      exchange_declaration_config:
        name: "rain_accumulator_topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

      publishing_config:
        exchange: "rain_accumulator_topic"
        mandatory: false
        immediate: false
        content_type: "application/json"

# ToDo: add EOF Manager queue and other data queues
