rainfall_threshold: 30.0

valid_columns:
  date: 2
  rainfall: 3

exchanges:
  exchange_input_weather: # messages from server to weather-worker
      name: "weather-topic"
      type: "topic"
      durable: true
      auto_deleted: false
      internal: false
      no_wait: false


  exchange_output_rain_joiner: # messages from weather-worker to rain accumulator
      name: "weather-rainjoiner-topic"
      type: "topic"
      durable: true
      auto_deleted: false
      internal: false
      no_wait: false

eof_queue_config: # queue of the eof manager
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false
