version: '3.9'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy

  client:
    container_name: client
    image: client:latest
    entrypoint: ./main
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - server

  broker1:
    container_name: broker1
    image: brokers:latest
    entrypoint: ./main
    environment:
      - BROKER_ID=1
      - CITY=montreal
      - BROKER_TYPE=weather-broker
      - FINISH_PROCESSING_MESSAGE=weather-PONG
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - rabbit
      - server

  broker2:
    container_name: broker2
    image: brokers:latest
    entrypoint: ./main
    environment:
      - BROKER_ID=2
      - CITY=montreal
      - BROKER_TYPE=weather-broker
      - FINISH_PROCESSING_MESSAGE=weather-PONG
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - rabbit
      - server

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - bikers
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

networks:
  bikers:
    name: bikers