version: '3.9'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy
      eof_manager:
        condition: service_started
      tw_montreal_1:
        condition: service_started
      ww_montreal_1:
        condition: service_started
      city_joiner_montreal_1:
        condition: service_started

  client:
    container_name: client
    image: client:latest
    entrypoint: ./main
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      eof_manager:
        condition: service_started
      server:
        condition: service_started

  eof_manager:
    container_name: eof_manager
    image: eofmanager:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy

  ww_montreal_1:
    container_name: ww_montreal_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=weather-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - city_joiner_montreal_1

  tw_montreal_1:
    container_name: tw_montreal_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - city_joiner_montreal_1

  sw_montreal_1:
    container_name: sw_montreal_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - city_joiner_montreal_1

  city_joiner_montreal_1:
    container_name: city_joiner_montreal_1
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q1
      - CITY=montreal
      - JOINER_TYPE=city-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

networks:
  bikers:
    name: bikers