version: '3.9'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy
      eof_manager:
        condition: service_started
      tw_montreal_1:
        condition: service_started
      tw_montreal_2:
        condition: service_started
      tw_montreal_3:
        condition: service_started
      sw_montreal_1:
        condition: service_started
      sw_montreal_2:
        condition: service_started
      sw_montreal_3:
        condition: service_started

      tw_toronto_1:
        condition: service_started
      tw_toronto_2:
        condition: service_started
      tw_toronto_3:
        condition: service_started
      sw_toronto_1:
        condition: service_started
      sw_toronto_2:
        condition: service_started
      sw_toronto_3:
        condition: service_started

      tw_washington_1:
        condition: service_started
      tw_washington_2:
        condition: service_started
      tw_washington_3:
        condition: service_started
      sw_washington_1:
        condition: service_started
      sw_washington_2:
        condition: service_started
      sw_washington_3:
        condition: service_started


  client:
    container_name: client
    image: client:latest
    entrypoint: ./main
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./datasets/:/client/datasets/

  eof_manager:
    container_name: eof_manager
    image: eofmanager:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy


  ### TRIP WORKERS

  tw_montreal_1:
    container_name: tw_montreal_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4

  tw_montreal_2:
    container_name: tw_montreal_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=montreal
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4

  tw_montreal_3:
    container_name: tw_montreal_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=montreal
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4


  tw_toronto_1:
    container_name: tw_toronto_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=toronto
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4

  tw_toronto_2:
    container_name: tw_toronto_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=toronto
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4

  tw_toronto_3:
    container_name: tw_toronto_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=toronto
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4


  tw_washington_1:
    container_name: tw_washington_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=washington
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4

  tw_washington_2:
    container_name: tw_washington_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=washington
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4

  tw_washington_3:
    container_name: tw_washington_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=washington
      - WORKER_TYPE=trips-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4


  ### STATION WORKERS

  sw_montreal_1:
    container_name: sw_montreal_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4

  sw_montreal_2:
    container_name: sw_montreal_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=montreal
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4

  sw_montreal_3:
    container_name: sw_montreal_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=montreal
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_montreal_1
      - year_joiner_montreal_2
      - year_joiner_montreal_3
      - year_joiner_montreal_4


  sw_toronto_1:
    container_name: sw_toronto_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=toronto
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4

  sw_toronto_2:
    container_name: sw_toronto_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=toronto
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4

  sw_toronto_3:
    container_name: sw_toronto_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=toronto
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_toronto_1
      - year_joiner_toronto_2
      - year_joiner_toronto_3
      - year_joiner_toronto_4


  sw_washington_1:
    container_name: sw_washington_1
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=washington
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4


  sw_washington_2:
    container_name: sw_washington_2
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=2
      - CITY=washington
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4

  sw_washington_3:
    container_name: sw_washington_3
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=3
      - CITY=washington
      - WORKER_TYPE=stations-worker
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - year_joiner_washington_1
      - year_joiner_washington_2
      - year_joiner_washington_3
      - year_joiner_washington_4


  ### JOINERS

  #### YEAR JOINER

  year_joiner_montreal_1:
    container_name: year_joiner_montreal_1
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q1
      - CITY=montreal
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_montreal # 1 por ciudad

  year_joiner_montreal_2:
    container_name: year_joiner_montreal_2
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q2
      - CITY=montreal
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_montreal # 1 por ciudad

  year_joiner_montreal_3:
    container_name: year_joiner_montreal_3
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q3
      - CITY=montreal
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_montreal # 1 por ciudad

  year_joiner_montreal_4:
    container_name: year_joiner_montreal_4
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q4
      - CITY=montreal
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_montreal # 1 por ciudad


  year_joiner_toronto_1:
    container_name: year_joiner_toronto_1
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q1
      - CITY=toronto
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_toronto # 1 por ciudad

  year_joiner_toronto_2:
    container_name: year_joiner_toronto_2
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q2
      - CITY=toronto
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_toronto # 1 por ciudad

  year_joiner_toronto_3:
    container_name: year_joiner_toronto_3
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q3
      - CITY=toronto
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_toronto # 1 por ciudad

  year_joiner_toronto_4:
    container_name: year_joiner_toronto_4
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q4
      - CITY=toronto
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_toronto # 1 por ciudad


  year_joiner_washington_1:
    container_name: year_joiner_washington_1
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q1
      - CITY=washington
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_washington # 1 por ciudad

  year_joiner_washington_2:
    container_name: year_joiner_washington_2
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q2
      - CITY=washington
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_washington # 1 por ciudad

  year_joiner_washington_3:
    container_name: year_joiner_washington_3
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q3
      - CITY=washington
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_washington # 1 por ciudad

  year_joiner_washington_4:
    container_name: year_joiner_washington_4
    image: joiners:latest
    entrypoint: ./main
    environment:
      - JOINER_ID=Q4
      - CITY=washington
      - JOINER_TYPE=year-joiner
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit
      - duplicates_handler_washington # 1 por ciudad

  ### HANDLERS

  #### DUPLICATES HANDLER

  duplicates_handler_montreal:
    container_name: duplicates_handler_montreal
    image: queryhandlers:latest
    entrypoint: ./main
    environment:
      - CITY=montreal
      - HANDLER_TYPE=duplicates-handler
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit

  duplicates_handler_toronto:
    container_name: duplicates_handler_toronto
    image: queryhandlers:latest
    entrypoint: ./main
    environment:
      - CITY=toronto
      - HANDLER_TYPE=duplicates-handler
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit

  duplicates_handler_washington:
    container_name: duplicates_handler_washington
    image: queryhandlers:latest
    entrypoint: ./main
    environment:
      - CITY=washington
      - HANDLER_TYPE=duplicates-handler
      - LOG_LEVEL=DEBUG
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    depends_on:
      - eof_manager
      - rabbit

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbit:5672/
    networks:
      - bikers
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

networks:
  bikers:
    name: bikers