version: '3.9'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - rabbit

  client:
    container_name: client
    image: client:latest
    entrypoint: ./main
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - server

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - bikers

networks:
  bikers:
    name: bikers