version: '3.9'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ./main
    environment:
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      rabbit:
        condition: service_healthy

  client:
    container_name: client
    image: client:latest
    entrypoint: ./main
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - server

  worker:
    container_name: worker
    image: workers:latest
    entrypoint: ./main
    environment:
      - WORKER_ID=1
      - CITY=montreal
      - WORKER_TYPE=weather-worker
      - LOG_LEVEL=DEBUG
    networks:
      - bikers
    depends_on:
      - rabbit
      - server

  rabbit:
    container_name: rabbit
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - bikers
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

networks:
  bikers:
    name: bikers