valid_columns:
  start_date: 2
  start_station_code: 3
  end_date: 4
  end_station_code: 5
  duration: 6
  year_id: 8

rabbit_mq:
  trips:
    exchange_input_trips: # messages from server to trip-worker
      exchange_declaration_config:
        name: "trips-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

    exchange_output_trips_rain: # messages from trip-worker to rain joiner
      exchange_declaration_config:
        name: "trips-rain-joiner-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false


    exchange_output_trips_year_filter: # messages from trip-worker to duplicate joiner
      exchange_declaration_config:
        name: "trips-duplicate-joiner-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

    exchange_output_trips_montreal_filter: # messages from trip-worker to montreal joiner
      exchange_declaration_config:
        name: "trips-montreal-joiner-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false
