valid_columns:
  start_date: 2
  start_station_code: 3
  end_date: 4
  end_station_code: 5
  duration: 6
  year_id: 8

exchanges:
  exchange_input_trips: # messages from server to trip-worker
    name: "trips-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_trips_rain: # messages from trip-worker to rain joiner
    name: "trips-rain-joiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false


  exchange_output_trips_year_filter: # messages from trip-worker to duplicate joiner
    name: "trips-duplicate-joiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_trips_montreal_filter: # messages from trip-worker to montreal joiner
    name: "trips-montreal-joiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

eof_queue_config: # queue of the eof manager
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false