valid_columns:
  start_date: 2
  start_station_code: 3
  end_date: 4
  end_station_code: 5
  duration: 6
  year_id: 8

data_delimiter: '|'
data_field_delimiter: ','
end_batch_marker: 'PING'

include_years: [2016, 2017]
include_cities: ["montreal"]
input_exchange: "trips-topic"

exchanges:
  exchange_input_trips: # messages from server to trip-worker
    name: "trips-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_rain_joiner: # messages from trip-worker to rain joiner
    name: "trips-rainjoiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false


  exchange_output_year_joiner: # messages from trip-worker to year joiner
    name: "trips-yearjoiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_montreal_joiner: # messages from trip-worker to montreal joiner
    name: "trips-montrealjoiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

eof_queue_config: # queue of the eof manager
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false