port: "12345"
ip: "server"
end_batch_marker: "PING"
ack_message: "PONG"
data_delimiter: "|"
max_amount_of_connections: 5
packet_limit: 8192 # 8 * 1024
protocol: "tcp"
fin_messages:
  - "weather-PONG"
  - "stations-PONG"
  - "trips-PONG"

queues:
  weather_filter_queue:
    name: "weather_filter_queue"
    declaration_config:
      durable: true
      delete_when_unused: false
      exclusive: false
      no_wait: false

    publishing_config:
      exchange: ""
      mandatory: false
      content_type: "text/plain"
