port: "12345"
ip: "server"
end_batch_marker: "PING"
ack_message: "PONG"
data_delimiter: "|"
max_amount_of_connections: 5
packet_limit: 8192 # 8 * 1024
protocol: "tcp"
fin_messages:
  - "weather-PONG"
  - "stations-PONG"
  - "trips-PONG"

rabbit_mq:
    weather:
      exchange_declaration_config:
        name: "weather-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

    trips:
      exchange_declaration_config:
        name: "trips-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

    stations:
      exchange_declaration_config:
        name: "stations-topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

# ToDo: add exchanges for other data types: stations and trips