valid_columns:
  code: 2
  name: 3
  latitude: 4
  longitude: 5
  year_id: 6

data_delimiter: '|'
data_field_delimiter: ','
end_batch_marker: 'PING'

include_years: [2016, 2017]
include_cities: ["montreal"]
input_exchange: "stations-topic"

exchanges:
  exchange_input_stations: # messages from server to station-worker
    name: "stations-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_year_joiner: # messages from station-worker to year joiner
    name: "stations-yearjoiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_city_joiner: # messages from station-worker to montreal joiner
    name: "stations-cityjoiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

eof_queue_config: # queue of the eof manager
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false
