valid_columns:
  code: 2
  name: 3
  latitude: 4
  longitude: 5
  year_id: 6

exchanges:
  exchange_input_stations: # messages from server to station-worker
    name: "stations-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_stations_year_filter: # messages from station-worker to duplicate joiner
    name: "stations-duplicate-joiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

  exchange_output_trips_montreal_filter: # messages from station-worker to montreal joiner
    name: "stations-montreal-joiner-topic"
    type: "topic"
    durable: true
    auto_deleted: false
    internal: false
    no_wait: false

eof_queue_config: # queue of the eof manager
  name: "eof-queue"
  durable: true
  delete_when_unused: false
  exclusive: true
  no_wait: false
