valid_columns:
  code: 2
  name: 3
  latitude: 4
  longitude: 5
  year_id: 6

rabbit_mq:
  station:
    exchange_input_station: # messages from server to station-worker
      exchange_declaration_config:
        name: "station_topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

      consumption_config:
        exchange: "station_topic"
        mandatory: false
        immediate: false
        content_type: "text/plain"

      queue_declaration_config: # Anonymous queue for consuming messages
        durable: true
        delete_when_unused: false
        exclusive: true
        no_wait: false

    exchange_output_station_year_filter: # messages from station-worker to year filter
      exchange_declaration_config:
        name: "year_filter_topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

      publishing_config:
        exchange: "year_filter_topic"
        mandatory: false
        immediate: false
        content_type: "application/json"

    exchange_output_station_montreal_filter: # messages from station-worker to montreal filter
      exchange_declaration_config:
        name: "montreal_filter_topic"
        type: "topic"
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false

      publishing_config:
        exchange: "montreal_filter_topic"
        mandatory: false
        immediate: false
        content_type: "application/json"