@startuml
'https://plantuml.com/class-diagram

class Metadata {
    + City string
	+ Type string
	+ Stage string
	+ Message string

	+ GetType()
	+ GetCity()
	+ GetStage()
	+ GetMessage()
}

class StationData {
	+ Code int
	+ Name string
	+ Latitude string
	+ Longitude string
	+ YearID int

	GetMetadata()
	GetPrimaryKey()
	HasValidCoordinates()
	GetCoordinates()
}

class WeatherData {
	+ Date Time
	+ Rainfall float64

	GetMetadata()
}

class TripData {
	+ Code int
	+ StartDate Time
	+ StartStationCode int
	+ EndDate Time
	+ EndStationCode int
	+ Duration float64
	+ YearID int

	GetMetadata()
}

class WeatherWorker {
    config WeatherConfig
}

class TripWorker {
    config TripWorker
}

class StationWorker {
    config TripWorker
}

Metadata <.up. StationData
Metadata <.up. WeatherData
Metadata <.up. TripData

StationData <.up. StationWorker
WeatherData <.up. WeatherWorker
TripData <.up. TripWorker

@enduml